# $Id: Makefile.purify,v 1.10 2008/05/13 18:41:28 brideout Exp $
#
# ----------------------------------------------------------------------
#       Solaris makefile for libgeo (Distribution version)
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
#       Site-dependent definitions - change these as needed
# ----------------------------------------------------------------------

# Madrigal root directory

# Solaris Make program

# Solaris Fortran compiler
FC = /opt/local/SUNWspro/bin/f77

# Solaris C compiler

# Library directory
LIBDIR = $(MADROOT)/lib/solaris

# Solaris Binary directory
BINDIR = $(MADROOT)/bin/solaris

# ----------------------------------------------------------------------
#       End of site-dependent definitions
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
#       Print Command
# ----------------------------------------------------------------------

PRINT = lp

# ----------------------------------------------------------------------
#       Library directives
# ----------------------------------------------------------------------

LDLIBS = -L$(LIBDIR) -lm -lnsl

# ----------------------------------------------------------------------
#       Fortran compiler options
# ----------------------------------------------------------------------

FFLAGS = -PIC -g

# ----------------------------------------------------------------------
#       Link editor options 
# ----------------------------------------------------------------------

LDFLAGS = -R$(LIBDIR)

# ----------------------------------------------------------------------
#       Fortran source files
# ----------------------------------------------------------------------

SOURCES = carmel.f convrt.f coord.f csconv.f diplat.f dsf.f gaspct.f \
          gdmag.f gdran.f gdv.f gmet.f gtd7.f hfun.f integ.f invar.f \
          invlat.f iterat.f  lines.f lintra.f look.f milmag.f minv.f \
          mtran3.f point.f rfun.f rpcart.f sprod.f startr.f          \
          tnf.f vadd.f vctcnv.f vmag.f vsub.f geo-cgm.f              \
          T01_01.f Geopack_2005.f                                    \
	  cgm_to_altitude.f altitude_to_cgm.f sfc_convert_geo_coord.f \
	  rylm.f blkdat95.f isrim.f basis.f conduct.f irisub.f       \
          irifun.f cira.f igrf.f iritec.f iridreg.f

# ----------------------------------------------------------------------
#       Object files
# ----------------------------------------------------------------------
OBJECTS = $(SOURCES:%.f=%.o)

# ----------------------------------------------------------------------
#       Libraries and Programs
# ----------------------------------------------------------------------

all: clean testGeolib sfctest testISRIM


testGeolib: testGeolib.o $(OBJECTS)
	purify $(LINK.f) testGeolib.o $(OBJECTS) $(LDLIBS) -o $@

	
sfctest: sfctest.o $(OBJECTS)
	purify $(LINK.f) sfctest.o $(OBJECTS) $(LDLIBS) -o $@
	
testISRIM: testISRIM.o $(OBJECTS)
	purify $(LINK.f) testISRIM.o $(OBJECTS) $(LDLIBS) -o $@

# ----------------------------------------------------------------------
#       Utility
# ----------------------------------------------------------------------

clean cleanup:
	rm -f testGeolib testGeolibs libgeo.a libgeo.so.1 sfctest \
              core *.o *.BAK *.CKP *% testISRIM
print listing:
	$(PRINT) Makefile $(SOURCES) testGeolib.f testGeolib.out.rock
