#!/Users/mnicolls/Documents/Work/Madrigal/bin/python

"""configureExperiments is a script to allow experiments to be imported from
other Madrigal installations.  Verifies both siteId and cgiUrl.

Replaces the tcl version of the same name

No arguments.

For each non-hidden local experiment, will make the following changes if needed:

    1. expTab.txt -> expId: set to new siteId x 10,000,000
    2. expTab.txt -> url: set to new url
    3. expTab.txt -> siteId: set to new siteId
    4. fileTab.txt -> fileId: set to new siteId x 10,000,000

$Id: configureExperiments.py,v 1.6 2009/04/16 20:20:00 brideout Exp $
"""

import os, os.path, sys

import madrigal.metadata

print 'configureExperiments is converting any experiment from a different' + \
      ' Madrigal site into a local experiment'

madDB = madrigal.metadata.MadrigalDB()
siteId = madDB.getSiteID()

thisId = siteId*10000000
cgiUrl = madDB.getCGIHomeBase()
cgiUrlTest = os.path.join(cgiUrl, 'madtoc')

# be sure experiments/stage exists and is world-writable
madroot = madDB.getMadroot()
stageDir = os.path.join(madroot, 'experiments/stage')
if not os.access(stageDir, os.R_OK):
    os.makedirs(stageDir)
try:
    os.chmod(stageDir, 0777)
except:
    pass


expConvertedNum = 0

# get a list of every Madrigal experiment directory
madExpDirs = madDB.getExpList()

for thisDir in madExpDirs:

    # create experiment object
    try:
        madExpObj = madrigal.metadata.MadrigalExperiment(madDB,
                                                         os.path.join(thisDir,
                                                                      'expTab.txt'))
    except:
        print 'WARNING - error with experiment %s expTab.txt file' % (thisDir)
        continue
    
    # if siteId is and cgiUrl is correct, continue
    if madExpObj.getExpSiteIdByPosition(0) == siteId and \
       madExpObj.getExpUrlByPosition(0).find(cgiUrlTest) != -1:
        continue

    print 'Modifying exp %s to be local' % (thisDir)
    expConvertedNum += 1

    # modify expTab.txt
    madExpObj.setExpIdByPosition(0, thisId)
    thisUrl = madExpObj.getExpUrlByPosition(0)
    newUrl = cgiUrl + '/madtoc/' + thisUrl.split('/madtoc/')[1]
    madExpObj.setExpUrlByPosition(0, newUrl)
    madExpObj.setExpSiteIdByPosition(0, siteId)
    madExpObj.writeMetadata()

    if os.access(os.path.join(thisDir,'fileTab.txt'), os.R_OK):
            
        try:
            madFileObj = madrigal.metadata.MadrigalMetaFile(madDB,
                                                            os.path.join(thisDir,
                                                                         'fileTab.txt'))
        except:
            print 'WARNING - error with experiment %s fileTab.txt' % (thisDir)
            continue

        # modify fileTab.txt
        madFileObj.setExpIdByPosition(0, thisId)
        madFileObj.writeMetadata()

if expConvertedNum == 0:
    print 'No non-local experiments found'
else:
    print 'configureExperiments done'
    

