#!/bin/sh
#
#   This script installs the entire Madrigal database.  Use -n to skip python installation
#
# See the latest documentation at http://madrigal.haystack.mit.edu/madrigal/admin.html
#   for the latest installation instructions
#
# $Id: installMadrigal,v 1.7 2009/01/27 19:47:49 brideout Exp $

# verify we are indeed in the right pwd
if [ ! -f installMadrigal ]
then
   echo "You must run this script from the MADROOT directory"
   exit -1
fi

# if MADROOT is set, be sure it matches PWD
if [ "$MADROOT" != "" ]
then
   if [ $MADROOT != $PWD ]
   then
      echo "Environmental variable MADROOT = $MADROOT does not match PWD = $PWD"
      exit -1
   fi
else
   export MADROOT=$PWD
fi

# check whether test experiments have been installed
if [ ! -f experiments/1998/mlh/20jan98/mil980120g.002 ]
then
   echo "The standard test data must be installed before installing Madrigal"
   echo "See install instructions at http://madrigal.haystack.mit.edu/madrigal/ad_install.html"
   echo "Standard test experiments can be found at http://madrigal.haystack.mit.edu/madrigal/madDownload.html"
   exit -1
fi

# check if python should be installed
python=1
if [ $# -gt 0 ]
then
   for arg in $@
   do
      if [ $arg = "-n" ]
      then
         python=0
      fi
   done
fi


# use the tclsh to run simple installation scripts
TCLSH=$(which tclsh)
if [ "$TCLSH" = "" ]
then
   echo
   echo "tclsh needs to be installed and in PATH"
   exit -1
fi

echo "Installing Madrigal in $MADROOT"

# verify correctness of madrigal.cfg
if [ ! -f madrigal.cfg ]
then
   echo
   echo "madrigal.cfg must be created first by copying madrigal.cfg.template and editing as needed"
   exit -1
else
   $TCLSH checkConfig
   if [ $? -ne 0 ]
   then
       exit -1
   fi
fi

# Set all file permissions to owner and group write
echo "********** setPermissions **********"
$TCLSH setPermissions
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** configureSource **********"
$TCLSH configureSource
if [ $? -ne 0 ]
then
    exit -1
fi

# Compile the Libraries and Programs
# ----------------------------------
cd source

echo "********** ./configure **********"
./configure --prefix=$MADROOT
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** make clean **********"
#make clean
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** make **********"
make
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** make check **********"
make check
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** make install **********"
make install
if [ $? -ne 0 ]
then
    exit -1
fi

cd ..

echo "********** configureHtml **********"
$TCLSH configureHtml
if [ $? -ne 0 ]
then
    exit -1
fi

echo "********** configureScripts **********"
$TCLSH configureScripts
if [ $? -ne 0 ]
then
    exit -1
fi


# Install python madrigal api and PyXML
# ----------------------------------
if [ $python = 1 ]
then
    echo "********** Installing local copy of python **********"
    cd source/madpy/pyxml
    tar -xf Python-2.5.2.tar
    cd Python-2.5.2
    ./configure --prefix=$MADROOT
    make
    make install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    cd ..
    rm -r Python-2.5.2
    echo "********** Installing madrigal python library **********"
    cd ..
    rm -f -r build
    $MADROOT/bin/python setup.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    rm -f -r build
    $MADROOT/bin/python setupMadrigalWeb.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    cd pyxml
    tar -xf PyXML-0.8.4.tar
    cd PyXML-0.8.4
    $MADROOT/bin/python setup.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    cd ..
    rm -r PyXML-0.8.4
    tar -xf numpy-1.0.4.tar
    cd numpy-1.0.4
    $MADROOT/bin/python setup.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    cd ..
    rm -r  numpy-1.0.4
    tar -xf  matplotlib-0.91.3.tar
    cd matplotlib-0.91.3
    $MADROOT/bin/python setup.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    cd ..
    rm -r matplotlib-0.91.3
    cd ../../..
else
    echo "********** Installing madrigal python library **********"
    cd source/madpy
    rm -f -r build
    $MADROOT/bin/python setup.py install
    if [ $? -ne 0 ]
    then
        exit -1
    fi
    rm -f -r build
    cd ../..
fi

# Install Experiments
# -------------------
echo "********** configureExperiments **********"
./configureExperiments
if [ $? -ne 0 ]
then
    exit -1
fi

# Update metadata
# -------------------
echo "********** Updating metadata tables **********"
bin/updateMaster
if [ $? -ne 0 ]
then
    exit -1
fi
echo "********** The following script will update fileTab.txt files **********"
bin/updateFileTab.py
if [ $? -ne 0 ]
then
    exit -1
fi
echo "********** Second call to updateMaster now needed **********"
bin/updateMaster
if [ $? -ne 0 ]
then
    exit -1
fi
echo "********** The following script will create all the summary files needed **********"
bin/rebuildInstParmTab.py -all
if [ $? -ne 0 ]
then
    exit -1
fi


# Test the Libraries and Programs
echo "********** Testing installation **********"
# ------------------------------
bin/testGeolib
if [ $? -ne 0 ]
then
    exit -1
fi
echo "--diff testGeolib.out source/madf/geolib/testGeolib.out.rock"
diff testGeolib.out source/madf/geolib/testGeolib.out.rock

bin/testMadrec > testMadrec.out
if [ $? -ne 0 ]
then
    exit -1
fi
echo "--diff testMadrec.out source/madc/madrec/testMadrec.out.rock"
diff testMadrec.out source/madc/madrec/testMadrec.out.rock

bin/madtclsh source/madc/madtcl/testMadtcl > testMadtcl.out
if [ $? -ne 0 ]
then
    exit -1
fi
echo "--diff testMadtcl.out source/madc/madrec/testMadrec.out.rock"
diff testMadtcl.out source/madc/madrec/testMadrec.out.rock

echo "running test on Madrigal web services..."
bin/python source/madpy/madrigalWeb/examples/testMadrigalWebServices.py

echo ""
echo "checking whether this system is 64 bit or greater"
bin/python source/madpy/scripts/bin/test64.py


# Install complete
# ---------------------
echo ""
echo "Madrigal installation complete"

