#!/bin/sh
# The madtclsh path is longer than 32 characters. So, we take advantage
# of the fact that a backslash continues a comment line in tcl \
exec MADROOT/bin/madtclsh "$0" ${1+"$@"}

# $Id: getMetadata,v 1.8 2008/03/14 15:29:22 brideout Exp $

# The following 2 procedures parse http query strings

proc subhex {v} {
    set nv $v
    while {[regexp {%[0-9A-F][0-9A-F]} $v blah]} {
        scan $blah "%%%x" cv
        if {[ctype char $cv]=="&"} {
            regsub -all $blah $v \\& nv
        } else {
            regsub -all $blah $v [ctype char $cv] nv
        }
        set v $nv
    }
    return $v
}

proc http_proc_args {arg} {
    global ar artype

    set bigarg {}
    set bigarg [split $arg &]
    set args {}

    foreach arg [concat $bigarg $args] {
        if [regexp {(.*)=(.*)} $arg foo name value] {
            set name [subhex $name]
            if ![info exists argcount($name)] {
                set argcount($name) 1
            } else {
                incr argcount($name)
            }
        }
    }
            
    #split assignments on the '&' 
    foreach arg [concat $bigarg $args] {
        if [regexp {(.*)=(.*)} $arg foo name value] {
            regsub -all {\+} $value { } newval
            set name [subhex $name]
            set val [subhex $newval]
            if ![info exists ar($name)] {
                if [info exists artype($name)] {
                    if {$artype($name)=="list"} {
                        if {$val!=""} {
                            set ar($name) [list $val]
                        } else {
                            set ar($name) {}
                        }
                    } else {
                        set ar($name) $val
                    }
                } else {
                    set ar($name) $val
                }
            } else {
                # multiple selection
                lappend ar($name) $val
            }
        }
    }
}

# Send form to the browser.  This is done when the server is
# called with no arguments.

proc send_form {} {

    global action
    
    puts "<TITLE>Madrigal Metadata Server</TITLE>"
    
    puts "<H1><CENTER>Madrigal Metadata Server</CENTER></H1>"
    
    puts "<HR>"
    
    puts "<FORM METHOD=\"POST\" ACTION=\"$action\">"
    
    puts "<PRE>"
    
    puts "<B>    Data Source</B>"

    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"0\"CHECKED> Experiment Table"
  
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"1\"> File Table"
  
    # dataTab.txt is now deprecated.  The value 2 still works, but no longer shows up
    # puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"2\"> Data Table"
  
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"3\"> Instrument Table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"4\"> Parameter Code Table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"5\"> Site Table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"6\"> Type Table"

    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"7\"> Instrument Kindat Table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"8\"> Instrument Parameter Table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"9\"> Madrigal categories table"
    
    puts "<INPUT TYPE=\"radio\" NAME=\"fileType\" VALUE=\"10\"> Instrument categories table"
    
    
    puts "</PRE>"
    
    puts "<HR>"
    
    puts "<CENTER><INPUT TYPE=\"submit\" VALUE=\"Get Table\"></CENTER> <P>"
    
    puts "</FORM>"
}


# Start Execution Here

 set metadir MADROOT/metadata
 set action getMetadata

# Query method is get - java applets use this.
if {[info exists env(QUERY_STRING)] && \
    [string length $env(QUERY_STRING)] > 0} {
    set msg $env(QUERY_STRING)
    set method get
    set have_parms 1
    puts "Content-type: text/plain\n"

# Query method is post - forms use this
} elseif {[info exists env(CONTENT_LENGTH)]} {
    set clen $env(CONTENT_LENGTH)
    set msg [read stdin $clen]
    set method post
    set have_parms 1
    puts "Content-type: text/html\n"

# No parameters - Instead of data a form will be returned.
} else {
    set method none
    set have_parms 0
    puts "Content-type: text/html\n"
}
# We have parameters.  So process them and send the requested data.

if {$have_parms == 1} {
    if {[string compare $method post] == 0} {puts "<PRE>"}

    # process arguments

    # Get form fillout parameters 
    http_proc_args $msg

    catch {set fileType $ar(fileType)}

    if {$fileType == 0} {
        set fileName $metadir/expTab.txt
        set fn "Experiment Table"
    } elseif {$fileType == 1} {
        set fileName $metadir/fileTab.txt
        set fn "File Table"
    } elseif {$fileType == 2} {
        set fileName $metadir/dataTab.txt
        set fn "Data Table"
    } elseif {$fileType == 3} {
        set fileName $metadir/instTab.txt
        set fn "Instrument Table"
    } elseif {$fileType == 4} {
        set fileName $metadir/parcods.tab
        set fn "Parameter Code Table"
    } elseif {$fileType == 5} {
        set fileName $metadir/siteTab.txt
        set fn "Site Table"
    } elseif {$fileType == 6} {
        set fileName $metadir/typeTab.txt
        set fn "Type Table"
    } elseif {$fileType == 7} {
        set fileName $metadir/instKindatTab.txt
        set fn "Instrument Kindat Table"
    } elseif {$fileType == 8} {
        set fileName $metadir/instParmTab.txt
        set fn "Instrument Parameter Table"
    } elseif {$fileType == 9} {
        set fileName $metadir/madCatTab.txt
        set fn "Madrigal Categories Table"
    } elseif {$fileType == 10} {
        set fileName $metadir/instType.txt
        set fn "Instrument Categories Table"
    }

    set fin [open $fileName]

    if {[string compare $method post] == 0} {
        puts "<TITLE>Madrigal Metadata Server</TITLE>"
        puts "<H1><CENTER>$fn</CENTER></H1>"
        puts "<HR>"
        puts "<FORM METHOD=\"POST\" ACTION=\"$action\">"    
        puts "<PRE>"
    }

    # Send the data
    while {[gets $fin line] >= 0} {
        puts $line
    }
    flush stdout

    if {[string compare $method post] == 0} {
        puts "</PRE>"
        #send_hidden_form
    }
    flush stdout

# This is first invocation.  So send form.
} else {
    send_form
}


