# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded mtl 1.0 [list tclPkgSetup $dir mtl 1.0 {{mtl.tcl source {delete madData madDataType madDataType_delete madData_delete madExp madExp_delete madExperiment madExperiment_delete madFile madFile_delete madInstrument madInstrument_delete madInventory madInventory_delete madRec madRec_delete madSite madSite_delete madrigal madrigal_delete mem metadata metadata_delete objdisp_madData objdisp_madDataType objdisp_madExp objdisp_madExperiment objdisp_madFile objdisp_madInstrument objdisp_madInventory objdisp_madRec objdisp_madSite objdisp_madrigal objdisp_metadata}} {mtl.imp source {calcJulianDay madDataType_exit madDataType_getEntries madDataType_init madDataType_print madDataType_read madDataType_write madData_addFile madData_exit madData_getEntries madData_init madData_print madData_read madData_write madExp_exit madExp_init madExp_print madExp_read madExp_write madExperiment_addFile madExperiment_exit madExperiment_generateFromFile madExperiment_getDataEntries madExperiment_getFileEntries madExperiment_init madExperiment_new madExperiment_print madExperiment_read madExperiment_updateFromFile madExperiment_write madFile_addFile madFile_exit madFile_getEntries madFile_init madFile_print madFile_read madFile_write madInstrument_exit madInstrument_getEntries madInstrument_init madInstrument_print madInstrument_read madInstrument_write madInventory_exit madInventory_getEntries madInventory_init madInventory_print madInventory_read madInventory_write madRec_exit madRec_init madRec_open madRec_print madSite_exit madSite_getEntries madSite_init madSite_print madSite_read madSite_write madrigal_exit madrigal_init madrigal_print metadata_exit metadata_init metadata_print translateCedarFile}}}]
