##########################  COMPILATION NEEDED LIBRARIES  ##########################
compile: clean compile-spectra

compile-spectra:
	cd lib/spec_worker && ${MAKE} clean && ${MAKE} compile

clean:
	cd lib/spec_worker && ${MAKE} clean
###########################################################################################